-- MySQL Script generated by MySQL Workbench
-- Sat Oct  7 08:39:22 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `eMail` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`username`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paper`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paper` (
  `idPaper` INT NOT NULL,
  `namaPaper` VARCHAR(45) NOT NULL,
  `User_username` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idPaper`),
  UNIQUE INDEX `namaPaper_UNIQUE` (`namaPaper` ASC),
  UNIQUE INDEX `idPaper_UNIQUE` (`idPaper` ASC),
  INDEX `fk_Paper_User1_idx` (`User_username` ASC),
  CONSTRAINT `fk_Paper_User1`
    FOREIGN KEY (`User_username`)
    REFERENCES `mydb`.`User` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kategori`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kategori` (
  `namaKategori` VARCHAR(20) NOT NULL,
  `Paper_idPaper` INT NOT NULL,
  PRIMARY KEY (`namaKategori`, `Paper_idPaper`),
  INDEX `fk_Kategori_Paper1_idx` (`Paper_idPaper` ASC),
  UNIQUE INDEX `namaKategori_UNIQUE` (`namaKategori` ASC),
  UNIQUE INDEX `Paper_idPaper_UNIQUE` (`Paper_idPaper` ASC),
  CONSTRAINT `fk_Kategori_Paper1`
    FOREIGN KEY (`Paper_idPaper`)
    REFERENCES `mydb`.`Paper` (`idPaper`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Penulis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Penulis` (
  `namaPenulis` VARCHAR(40) NOT NULL,
  `Paper_idPaper` INT NOT NULL,
  PRIMARY KEY (`namaPenulis`, `Paper_idPaper`),
  INDEX `fk_Penulis_Paper1_idx` (`Paper_idPaper` ASC),
  CONSTRAINT `fk_Penulis_Paper1`
    FOREIGN KEY (`Paper_idPaper`)
    REFERENCES `mydb`.`Paper` (`idPaper`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
